name: pr
on: [pull_request]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          find . -type d -print0 | xargs -0 chmod 777
          make aports
          make EMAIL=test@test.test genkeys
      - name: Lint
        run: make lint
      - name: Build image
        run: make build
